version: 0.1
phases:
  install:
    commands:
      - sam package --template-file template.yml --s3-bucket pipeline-demo-test1 --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml